new eci process to handle comunication between process (ecimsgh) this allow handling soft disconnect eciadsl-ctrui is the process that ask for disconnection

diff --git a/usermode/eciadsl-stop b/usermode/eciadsl-stop
--- a/usermode/eciadsl-stop
+++ b/usermode/eciadsl-stop
@@ -15,13 +15,16 @@ ps ax | grep "eciadsl-pppoeci" | grep -v grep > /dev/null 2>&1
 if [ $? -eq 0 ]; then
 	eciadsl-ctrlui --disconnect
     sleep 1
-    killall pppd
-    if [ $? -eq 0 ]; then
-        echo -e "stopped."
-    else
-        echo -e "failed to stop"
-        exit 2
-    fi
+	ps ax | grep "pppd" | grep -v grep > /dev/null 2>&1
+	if [ $? -eq 0 ]; then    
+    	killall pppd
+	    if [ $? -eq 0 ]; then
+	        echo -e "stopped."
+	    else
+	        echo -e "failed to stop"
+	        exit 2
+	    fi
+	fi
 else
     echo -e "failed (not running)"
     exit 1
