Check the path for pppoeci, since I misunderstood and put /usr/local/bin (which is also executable, but not a file!)

diff --git a/usermode/makeconfig b/usermode/makeconfig
--- a/usermode/makeconfig
+++ b/usermode/makeconfig
@@ -38,6 +38,12 @@ if [ $# -ne 5 ]; then
     exit 1
 fi
 
+pppoeci=$3
+if [ ! -f ${pppoeci} -o ! -x ${pppoeci} ]; then
+	echo "Error: ${pppoeci} is not a valid executable"
+	exit 1
+fi
+
 #
 # backup and create resolv.conf
 #
